version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: food-delivery-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ilovecookies
      MONGO_INITDB_DATABASE: nom
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data: